runs:
  using: "composite"
  steps:

    - name: clevertap-core-assembleRelease
      if: always()
      shell: bash
      run: ./gradlew :clevertap-core:assembleRelease

    - name: Upload AAR and apk files
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: clevertap-core-assembleRelease
        path: clevertap-core/build/outputs/aar

    ###------##----------###------##----------###------##----------###------##----------###------##----------###------##----------###------##----------

    - name: clevertap-geofence-assembleRelease
      if: always()
      shell: bash
      run: ./gradlew :clevertap-geofence:assembleRelease

    - name: Upload AAR and apk files
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: clevertap-geofence-assembleRelease
        path: clevertap-geofence/build/outputs/aar

    ###------##----------###------##----------###------##----------###------##----------###------##----------###------##----------###------##----------

    - name: clevertap-hms-assembleRelease
      if: always()
      shell: bash
      run: ./gradlew :clevertap-hms:assembleRelease

    - name: Upload AAR and apk files
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: clevertap-hms-assembleRelease
        path: clevertap-hms/build/outputs/aar

    ###------##----------###------##----------###------##----------###------##----------###------##----------###------##----------###------##----------

    - name: clevertap-pushTemplates-assembleRelease
      if: always()
      shell: bash
      run: ./gradlew :clevertap-pushtemplates:assembleRelease

    - name: Upload AAR and apk files
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: clevertap-pushTemplates-assembleRelease
        path:  clevertap-pushtemplates/build/outputs/aar

    ###------##----------###------##----------###------##----------###------##----------###------##----------###------##----------###------##----------

    - name: clevertap-xps-assembleRelease
      shell: bash
      run: ./gradlew :clevertap-xps:assembleRelease

    - name: Upload AAR and apk files
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: clevertap-xps-assembleRelease
        path: clevertap-xps/build/outputs/aar