name: Sample App Build
on:
  workflow_dispatch:
    github.event.inputs:
      build_debug_apk:
        description: Build Debug APK
        type: boolean
        default: true
        required: false

      build_debug_bundle:
        description: Build Debug Bundle
        type: boolean
        default: false
        required: false

      build_release_apk:
        description: Build Release APK
        type: boolean
        default: false
        required: false

      build_release_bundle:
        description: Build Release Bundle
        type: boolean
        default: false
        required: false


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code from Repo
        uses: actions/checkout@v3

      - name: Setup JDK 17.
        uses: ./.github/mini_flows/setup_jdk

      - name: Build Debug APK
        if: ${{ github.event.inputs.build_debug_apk == 'true'}}
        run: |
          ./gradlew :sample:assembleRemoteDebug

      - name: Build Debug Bundle
        if: ${{ github.event.inputs.build_debug_apk == 'true'}}
        run: |
          ./gradlew :sample:bundleRemoteDebug

      - name: Build Release APK
        if: ${{ github.event.inputs.build_release_apk == 'true'}}
        run: |
          ./gradlew :sample:assembleRemoteRelease


      - name: Build Release Bundle
        if: ${{ github.event.inputs.build_release_bundle == 'true'}}
        run: |
          ./gradlew :sample:bundleRemoteRelease

      - name: Upload Debug APK
        if: ${{ github.event.inputs.build_debug_apk == 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: sample-debug-apk
          path: sample/build/outputs/apk/remote/debug/*.apk

      - name: Upload Debug Bundle
        if: ${{ github.event.inputs.build_debug_bundle == 'true'}}
        uses: actions/upload-artifact@v3
        with:
          name: sample-debug-bundle
          path: sample/build/outputs/bundle/remoteDebug/*.aab

      - name: Upload Release APK
        if: ${{ github.event.inputs.build_release_apk == 'true'}}
        uses: actions/upload-artifact@v3
        with:
          name: sample-release-apk
          path: sample/build/outputs/apk/remote/release/*.apk


      - name: Upload Release Bundle
        if: ${{ github.event.inputs.build_release_bundle == 'true'}}
        uses: actions/upload-artifact@v3
        with:
          name: sample-release-bundle
          path: sample/build/outputs/bundle/remoteRelease/*.aab